# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T15:33:50+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, BaseSecurity

from models import (
    DgcerCertificatePostRequest,
    DgcerCertificatePostResponse,
    DgcerCertificatePostResponse1,
    DgcerCertificatePostResponse2,
    DgcerCertificatePostResponse3,
    DgcerCertificatePostResponse4,
    DgcerCertificatePostResponse5,
    DgcerCertificatePostResponse6,
)

app = MCPProxy(
    description="Veer Surendra Sai University Of Technology, Odisha (http://vssut.ac.in) is issuing Degree certificates through DigiLocker. These can be pulled by students into their DigiLocker accounts. Currently, data for the year's 2014-2019 is made available by Veer Surendra Sai University Of Technology.",
    termsOfService='https://apisetu.gov.in/terms.php',
    title='Veer Surendra Sai University Of Technology',
    version='3.0.0',
    servers=[{'url': 'https://apisetu.gov.in/vssut/v3'}],
)


@app.post(
    '/dgcer/certificate',
    description=""" API to verify Degree/ Diploma Certificate. """,
    tags=['certificate_management'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def dgcer(body: DgcerCertificatePostRequest = None):
    """
    Degree/ Diploma Certificate
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
